RandomForest:
  n_estimators : [int(x) for x in np.linspace(start = 10, stop = 80, num = 10)]
  max_features : ['sqrt', 'log2', None]
  max_depth : [None, 10, 20, 30]
  min_samples_split : [2, 5, 10]
  min_samples_leaf : [1, 2, 4]
  bootstrap : [True, False]
