

COLUMNS:
  CreditScore: int64
  Geography: int32
  Gender: int32
  Age: int64
  Tenure: int64
  Balance: int32
  NumOfProducts: int64
  IsActiveMember: int64
  EstimatedSalary: int32
  Exited: int64

TARGET_COLUMN:
  name: Exited



  
  # RowNumber: int64
  # CustomerId: int64
  # Surname: object
  # CreditScore: int64
  # Geography: object
  # Gender: object
  # Age: int64
  # Tenure: int64
  # Balance: float64
  # NumOfProducts: int64
  # HasCrCard: int64
  # IsActiveMember: int64
  # EstimatedSalary: float64

